import { ethers } from 'ethers';
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Domain from '../artifacts/contracts/Domain.sol/Domain.json';
import { useEffect } from 'react';
import axios from 'axios';
export default function Home() {
  const[domain,setDomain] = useState('');
  const[message, setMessage] = useState('');
  const[card,setCard]=useState(null)
  useEffect(()=>{
    connectWallet()
    },[])
  const connectWallet = async() =>{
    if(window.ethereum){
      const accounts = await window.ethereum.request({method:"eth_accounts"});
      if(accounts.length == 0){
        let account = await window.ethereum.request({method:"eth_requestAccounts"})
      }
   
    }
    else{
      console.log("Connect Your Metamask!!")
    }
  }
  const askDomain = (event) =>{
    setDomain(event.target.value);

  }
  const checkDomain = async ()=>{
    try{
      const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner();
    const contract = new ethers.Contract("0x20D6c84d435bE4D72B766Bf2b4288cD8214d77B0",Domain.abi,signer);

    let address = await contract.getAddress(domain);
    console.log(address);
    setMessage(address.toString());
    let record= await contract.getRecords(domain);
    console.log(record.tokenId.toNumber());
    const tokenUri=await contract.tokenURI(record.tokenId.toNumber());
    console.log(tokenUri);
    const meta = await axios.get(tokenUri);
    setCard(tokenUri)
    
    
    }
    catch(error){
      if(error.data){
        console.log(error);
        setMessage("Domain Available");

      }
    }
    
  }
  return (
    <div >
      <Head>
        <title>WIS</title>
        <meta name="description" content="Generated by identity for Web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=' outline p-6  bg-gradient-to-r from-purple-500 to-pink-500'>
        <h2 className="font-medium leading-tight text-4xl mt-0 mb-2 text-white">Welcome to Web3 Identity Services !!</h2>
        </div>
        <div className='flex bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4'>
          <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" onChange={askDomain} placeholder="Check the domain here"/>
          <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' onClick={checkDomain}>Check Domain</button>

        </div>
        {message && <div>Address: {message}</div>}

        {card &&<img src={card} width="320" height="320" id="idImage" />}           
        <div className="grid grid-cols-3 gap-4 bg-[url('/public/background.png')]" style ={{backgroundImage: `url(background.png)`,width:'100%'}}>
          <div className="m-10">
          <h2 className="font-medium leading-tight text-4xl mt-0 mb-2 text-white">Who we are?</h2>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>WIS main goal is to provide cheap domain service.</p>
              <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>We believe everyone is welcomed in Web3 and your identity should not be depended on your wallet.</p>
                <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>We are bunch of broke developers who could not afford ENS domain due to high gas fees so what we did- We created our own.</p>
                  <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'> We are non profit based means we will not charge any commision for creating the domain basically you have to pay on the gas fee of loygon which is very cheap compared to ethereum.</p>
          </div>
          <div className="m-10">
          <h2 className="font-medium leading-tight text-4xl mt-0 mb-2 text-white">How we can help?</h2>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>We can help you to create your own domain in Polygon</p>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>Domain provides a basic identity in WEb3. You can make transaction using your domain, help others to find you</p>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>We also provide a facility to create your own identity card as a NFT which you show to your fellow Web 3 enthuisastic and even sell or collect them!!</p>
          </div>
          <div className="m-10">
          <h2 className="font-medium leading-tight text-4xl mt-0 mb-2 text-white">Help us to improve</h2>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>This app is as limted to your developer imagination so you if you have better ideas to improve our sevice or you want to join our cool developer teams then do not hesitate</p>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>You can contact us <a href="/">here</a></p>
            <p className='text-base font-light leading-relaxed mt-0 mb-4 text-white'>You can help us to increase our reach by following us at our social media handles. Don't worry we are working on creating a Web3 based social media handle where you will own your content!!</p>
          </div>
        </div>
      </main>

      <footer className='bg-black p-8'>
        <a
          href="https://github.com/parshviSri"
          target="_blank"
          rel="noopener noreferrer"
          className='text-white'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logo.png" className="rounded-full"alt="Vercel Logo" width={72} height={56} />
          </span>
        </a>
      </footer>
    </div>
  )
}
